### PR TITLE
update hyper-pay to 2.8.0

### PR DESCRIPTION
**Pull request by shreyasheww**
- Add 2.8.0 android & iOS sdk file in location
- update SDK in gradle
- test example app inside hyper-pay

### CODE REVIEW

**Comment by pr-Mais** [comment]
Could you please solve the conflicts? Thanks.

**Comment by shreyasheww** [comment]
I can not able find conflicts, can you guild me on the above logs

**Comment by shreyasheww** [comment]
I have taken pull before starting work and cannot find the conflicts on my side. else guide me steps to solve

**Comment by pr-Mais** [comment]
Conflicts are still present, I closed this. Pull a fresh copy from main and try again.

**Pull request closed without merging**
